### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by aisabellafontes** [dsouzarc/pacman#1]
1. First compile all files *.java on linux  terminal, including jar classpath
javac -cp ~/github/pacman/cs015.jar *.java

2. After, I try running the application
java Pacman

3. And then, this message:
Exception in thread "main" java.lang.NoClassDefFoundError: cs015/fnl/PacmanSupport/SupportMap
	at Pacman.getBoard(Pacman.java:553)
	at Pacman.<init>(Pacman.java:42)
	at Pacman.main(Pacman.java:478)
Caused by: java.lang.ClassNotFoundException: cs015.fnl.PacmanSupport.SupportMap
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 3 more

I'm confused, can anyone help me?

**Comment by dsouzarc** [comment]
Hey, sorry about that. I updated the README.md to contain the compile and run commands.

Running Instructions (Commandline for Linux/OSX)

1. Download all files to the same directory

2. Compile the files

        javac -cp "cs015.jar" *.java


3. Run the main method of the Pacman.java file

        java -cp cs015.jar:. Pacman

**Comment by aisabellafontes** [comment]
Thanks a lot :)
